### ISSUE TITLE
Couple little things...

### ISSUE THREAD

**Issue by NathanWalker** [peoplewareDo/generator-nativescript-plugin#1]
@victorsosa This is amazingly cool and helpful, thank you so much for this!

Just a couple small things I noticed when playing around with this:
- When dashed name (like `action-wizard`) is used (when yeoman asks for name of plugin) some are camelCase and others are not:

```
"main": "actionWizard.js",
...
"url": "git+https://github.com/Nathan Walker/nativescript-actionWizard.git"
...
"name": "nativescript-action-wizard",
...
"preparedemo": "npm run build && cd demo && tns plugin remove nativescript-actionWizard && tns plugin add .. && tns install",
```

They should probably all be the same as user entered: `action-wizard`.
- The class that's generated should be title cased:

```
export class actionWizard extends Common {  // This should be ActionWizard
}
```
- A `gitignore` file should be added which should probably match what is on the seed here: https://github.com/NathanWalker/nativescript-plugin-seed/blob/master/.gitignore (Right now no `.gitignore` file is generated)

This is just soooo awesome, I can't thank you enough for the work here. I want to promote this a lot once we can get the above sorted out 👍

**Comment by victorsosa** [comment]
Hi,

The .gitignore issue is a well know npm issue :S, I can't figure out something right now, the workaround will be just create the .gitignore file.

https://github.com/npm/npm/issues/3763

The other issues are fixed:
- The class that's generated should be title cased
- When dashed name (like action-wizard) is used (when yeoman asks for name of plugin) some are camelCase and others... everything is dashed now.

Enjoy.. XD

**Comment by victorsosa** [comment]
Actually, you don't need to dash the input like "action-wizard" the generator do it for you, so if you input is "action wizard" it will dashed the input.

I have to Document that in the readme.
